"parser":
  "babel-eslint"
"parserOptions":
  "sourceType": "module"
"rules":
  "arrow-spacing": 2
  "camelcase": 2
  "comma-spacing":
    - 2
    - "before": false
      "after": true
  "curly": 2
  "eqeqeq": 2
  "indent":
    - 2
    - 2
  "jsx-quotes":
    - 2
    - "prefer-single"
  "no-cond-assign": 2
  "no-console": 1
  "no-constant-condition": 2
  "no-extra-semi": 2
  "no-magic-numbers":
    - 2
    - "ignoreArrayIndexes": true
  "no-spaced-func": 2
  "no-throw-literal": 2
  "no-trailing-spaces": 2
  "no-var": 2
  "prefer-arrow-callback": 2
  "prefer-const": 2
  "prefer-template": 2
  "radix": 2
  "semi":
    - 2
    - "always"
  "yoda": 2
