export const CLEAR_REGISTRATION_ERRORS = 'CLEAR_ERRORS';
export const END_SERVER_REGISTRATION = 'END_SERVER_REGISTRATION';
export const START_SERVER_REGISTRATION = 'START_SERVER_REGISTRATION';
export const TOGGLE_REGISTRATION = 'TOGGLE_REGISTRATION';
export const VALIDATE_REGISTRATION = 'VALIDATE_REGISTRATION';
