export const CREATE_USER = 'CREATE_USER';
export const CLEAR_REGISTRATION_ERRORS = 'CLEAR_ERRORS';
export const END_SERVER_REGISTRATION = 'END_SERVER_REGISTRATION';
export const SET_REGISTRATION_ERRORS = 'SET_SERVER_REGISTRATION_ERRORS';
export const START_SERVER_REGISTRATION = 'START_SERVER_REGISTRATION';
export const TOGGLE_REGISTRATION = 'TOGGLE_REGISTRATION';
export const TOGGLE_SUCCESS = 'TOGGLE_SUCCESS';
export const VALIDATE_REGISTRATION = 'VALIDATE_REGISTRATION';
